services:
  playwright:
    build:
      context: .
      dockerfile: ./Dockerfile.playwright
    command: pnpm e2e --ui
    environment:
      DISPLAY: ${DISPLAY}
    env_file: .env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}:/app
