services:
  playwright:
    build:
      context: .
      dockerfile: ./playwright.dockerfile
    command: pnpm e2e
    environment:
      DISPLAY: ${DISPLAY}
    env_file: .env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}:/app
    ports:
      - 9323:9323
